import { FieldTypeEnum, SurveyStep } from "../interfaces";

export const surveyMock: SurveyStep[] = [
  {
    title: 'Основные сведения',
    order: 1,
    sections: [
      {
        title: 'Клиент',
        expand: true,
        fields: [
          {
            label: 'First Name',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'first_name',
            value: null,
          },
          {
            label: 'Last Name',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'last_name',
            value: null,
          },
          {
            label: 'Middle Name',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'middle_name',
            value: null,
          },
          {
            label: 'Salutation',
            type: FieldTypeEnum.Select,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'salutation',
            value: null,
          },
          {
            label: 'Организационно-правовая форма',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'org_legal_form',
            value: null,
          },
        ],
        dependent: null,
      },
      {
        title: 'Сведения о государственной регистрации',
        fields: [
          {
            label: 'ОГРН',
            type: FieldTypeEnum.Number,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_ogrn',
            value: null,
          },
          {
            label: 'Дата регистрации',
            type: FieldTypeEnum.Date,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'date_of_registration',
            value: null,
          },
          {
            label: 'Наименование регистрирующего органа',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'registration_authority_name',
            value: null,
          },
          {
            label: 'Место регистрации',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'registration_authority_place',
            value: null,
          },
          {
            label: 'ИНН',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'inn',
            value: null,
          },
        ],
        expand: false,
        dependent: null,
      },
      {
        title: 'Адрес юридического лица',
        fields: [
          {
            label: 'Согласно учредительным документам',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_address_legal',
            value: null,
          },
          {
            label: 'Фактический адрес (если не совпадают)',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_address_fact',
            value: null,
          },
          {
            label:
              'Сведения о присутствии юридического лица и его постоянно действующих органов управления по адресу его местонахождения',
           type: FieldTypeEnum.Select,
            code: null,
            acceptableFieldValues: [
              {
                id: 13,
                value: 'Присутствует',
              },
              {
                id: 14,
                value: 'Не присутствует',
              },
            ],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_presence_information',
            value: null,
          },
        ],
        expand: false,
        dependent: null,
      },
      {
        title: '',
        fields: [
          {
            label: 'Интернет-сайт',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_site',
            value: null,
          },
          {
            label: 'E-mail',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_email',
            value: null,
          },
          {
            label: 'Телефон',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_phone',
            value: null,
          },
          {
            label: 'Контактное-лицо',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_contact_person',
            value: null,
          },
          {
            label: 'Численность работников',
            type: FieldTypeEnum.Number,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_employees_number',
            value: null,
          },
          {
            label: 'Филиалы и представительство',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_branches',
            value: null,
          },
          {
            label: 'Субъект МСП',
           type: FieldTypeEnum.Checkbox,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_subject_msp',
            value: null,
          },
          {
            label: 'Величина уставного капитала',
            type: FieldTypeEnum.Number,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_authorized_capital',
            value: null,
          },
          {
            label: 'Является ли Клиент частью Группы/Холдинга',
           type: FieldTypeEnum.Checkbox,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_is_part_of_group',
            value: null,
          },
          {
            label: 'Является ли Клиент частью Группы/Холдинга',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: 'client_is_part_of_group',
            slug: 'client_is_part_of_group_y',
            value: null,
          },
          {
            label:
              'Участие клиента в других организациях или совместная деятельность с другими организациями',
           type: FieldTypeEnum.Checkbox,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_participation',
            value: null,
          },
          {
            label:
              'Участие клиента в других организациях или совместная деятельность с другими организациями',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: 'client_participation',
            slug: 'client_participation_y',
            value: null,
          },
        ],
        expand: false,
        dependent: null,
      },
    ],
  },
  {
    title: 'Информация о деятельности',
    order: 2,
    sections: [
      {
        title: 'Основные виды деятельности',
        fields: [
          {
            label: 'Основная отрасль',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_main_industry',
            value: null,
          },
          {
            label: 'Основной вид ОКВЭД (код и расшифровка)',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_okved',
            value: null,
          },
          {
            label: 'ОКАТО',
            type: FieldTypeEnum.Number,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_okato',
            value: null,
          },
          {
            label: 'ОКПО',
            type: FieldTypeEnum.Number,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_okpo',
            value: null,
          },
        ],
        expand: false,
        dependent: null,
      },
      {
        title:
          'Сведение о лицензиях на право осуществления деятельности, подлежащей лицензированию',
        fields: [
          {
            label: 'Вид лицензии',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_licenses',
            value: null,
          },
          {
            label: 'Номер',
            type: FieldTypeEnum.Number,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_licenses_number',
            value: null,
          },
          {
            label: 'Дата выдачи',
            type: FieldTypeEnum.Date,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_licenses_date',
            value: null,
          },
          {
            label: 'Наименование органа, выдавшего лицензию',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_licenses_authority_name',
            value: null,
          },
          {
            label: 'Срок действия',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_licenses_term',
            value: null,
          },
        ],
        expand: false,
        dependent: null,
      },
      {
        title: 'Тип собственности',
        fields: [
          {
            label: 'Тип собственности',
           type: FieldTypeEnum.Select,
            code: null,
            acceptableFieldValues: [
              {
                id: 17,
                value: 'государственная организация',
              },
              {
                id: 18,
                value: 'негосударственная организация',
              },
            ],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_property_type',
            value: null,
          },
        ],
        expand: false,
        dependent: null,
      },
      {
        title: 'Цель бизнеса',
        fields: [
          {
            label: 'Цель бизнеса',
           type: FieldTypeEnum.Select,
            code: null,
            acceptableFieldValues: [
              {
                id: 19,
                value: 'коммерческая деятельность с целью извлечения прибыли',
              },
              {
                id: 20,
                value: 'некоммерческая деятельность',
              },
            ],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_business_target',
            value: null,
          },
        ],
        expand: false,
        dependent: null,
      },
      {
        title: 'Цель установления отношений с Банком',
        fields: [
          {
            label: 'Цель установления отношений с Банком',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_bank_relation_purpose',
            value: null,
          },
        ],
        expand: false,
        dependent: null,
      },
      {
        title: 'Предполагаемый характер отношений с Банком',
        fields: [
          {
            label: 'Предполагаемый характер отношений с Банком',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_bank_relation_nature',
            value: null,
          },
        ],
        expand: false,
        dependent: null,
      },
      {
        title: 'Сведения о деловой репутации юридического лица',
        fields: [
          {
            label: 'Сведения о деловой репутации юридического лица',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_business_reputation',
            value: null,
          },
        ],
        expand: false,
        dependent: null,
      },
      {
        title: 'Информация о счетах в банках',
        fields: [
          {
            label: 'Наименование банка',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_bank_account_name_table',
            value: null,
          },
          {
            label: 'Номер счета',
            type: FieldTypeEnum.Text,
            code: null,
            acceptableFieldValues: [],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_bank_account_number_table',
            value: null,
          },
        ],
        expand: true,
        dependent: null,
      },
      {
        title: 'Информация об источниках происхождения денежных средств и (или) иного имущества',
        fields: [
          {
            label:
              'Информация об источниках происхождения денежных средств и (или) иного имущества',
           type: FieldTypeEnum.Select,
            code: null,
            acceptableFieldValues: [
              {
                id: 15,
                value: 'Собственные средства',
              },
              {
                id: 16,
                value: 'Заемные средства',
              },
            ],
            description: null,
            required: true,
            condition: null,
            dependent: null,
            slug: 'client_sources_of_funds',
            value: null,
          },
        ],
        expand: false,
        dependent: null,
      },
    ],
  },
];